server:
  port: 9192

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/lakeside_db
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: root
#      password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB
  spring:


